export default {
    allLanguageList: [
        '‪Afrikaans‬',
        '‪azərbaycan‬',
        '‪bosanski‬',
        '‪català‬',
        '‪Dansk‬',
        '‪Deutsch‬',
        '‪eesti‬',
        '‪English (United Kingdom)‬',
        '‪Español (España)‬',
        '‪Español (Latinoamérica)‬',
        '‪euskara‬',
        '‪Filipino‬',
        '‪Français (Canada)‬',
        '‪Indonesia‬',
        '‪Nederlands‬',
        '‪ខ្មែរ‬',
        '‪galego‬',
        '‪srpski (latinica)‬',
        '‪polski‬',
        '‪Tiếng Việt‬',
        '‪հայերեն‬',
        '‪norsk‬',
        '‪ລາວ‬',
        '‪isiZulu‬',
        '‪繁體中文‬',
        '‪Українська‬',
        '‫العربية‬',
        '‪Français (France)‬',
        '‪magyar‬',
        '‪Suomi‬',
        '‪Ελληνικά‬',
        '‪Hrvatski‬',
        '‪Melayu‬',
        '‪Português (Portugal)‬',
        '‪தமிழ்‬',
        '‪አማርኛ‬',
        '‪latviešu‬',
        '‪ქართული‬',
        '‪Čeština‬',
        '‫עברית‬',
        '‪中文（香港）‬',
        '‪íslenska‬',
        '‪తెలుగు‬',
        '‪монгол‬',
        '‪සිංහල‬',
        '‪Русский‬',
        '‪नेपाली‬',
        '‪Türkçe‬',
        '‪română‬',
        '‪lietuvių‬',
        '‪हिन्दी‬',
        '‪Svenska‬',
        '‫فارسی‬',
        '‪മലയാളം‬',
        '‪한국어‬',
        '‪मराठी‬',
        '‪日本語‬',
        '‪български‬',
        '‪slovenščina‬',
        '‪ไทย‬',
        '‪македонски‬',
        '‪ਪੰਜਾਬੀ‬',
        '‪ગુજરાતી‬',
        '‪বাংলা‬',
        '‪Kiswahili‬',
        '‫اردو‬',
        '‪Português (Brasil)‬',
        '‪Slovenčina‬',
        '‪Italiano‬',
        '‪српски (ћирилица)‬',
        '‪မြန်မာ‬',
        '‪ಕನ್ನಡ‬',
        '‪简体中文‬'
    ],
};